Olavrenteva: Practice#4
IlyaOrlov/PythonCoursePro pull request #28
Opened 2021-10-01 19:25 UTC by OlgaLavrenteva

2021-10-02 12:51 UTC, IlyaOrlov commented on Practice/olavrenteva/practice4/task3.py
> +    sort_choice(array, start_index+1)
ОК. Только нужно иметь в виду, что Python ограничивает глубину рекурсии во избежание переполнения стека. Узнать допустимую глубину рекурсии можно так:
```python 
import sys
print(sys.getrecursionlimit())
```
Впрочем, глубину рекурсию можно и поменять (хотя это и нежелательно):
```python
sys.setrecursionlimit(2000)
```

2021-10-02 13:05 UTC, IlyaOrlov requested changes

2021-10-02 13:05 UTC, IlyaOrlov commented on Practice/olavrenteva/practice4/task6.py
> +            exclude_column(lst, value)
Не упростит ли алгоритм добавление break после 7-й строки?

2021-10-03 10:11 UTC, OlgaLavrenteva commented on Practice/olavrenteva/practice4/task6.py
> +            exclude_column(lst, value)
Если в матрице будет несколько строк с заданной цифрой в разных столбцах, то с break удалится только один столбец (тот, что первый встретится в строках). Но это же не то, что нам нужно?

2021-10-03 10:20 UTC, OlgaLavrenteva commented on Practice/olavrenteva/practice4/task3.py
> +    sort_choice(array, start_index+1)
Окей, запушила второй вариант решения, без рекурсии.

2021-10-03 10:30 UTC, IlyaOrlov commented on Practice/olavrenteva/practice4/task6.py
> +            exclude_column(lst, value)
Например, так (удаляем столбцы с 2):
```python
matrix = [
    [2, 15, -10, 1],
    [3, 2, 4, 100],
    [1, 16, 2, 0]
]
```
Все удаляется корректно, благодаря рекурсии:
```
[[1], [100], [0]]
```

2021-10-03 10:34 UTC, IlyaOrlov commented on Practice/olavrenteva/practice4/task3.py
> +    sort_choice(array, start_index+1)
Отлично! Вообще, я ничего против рекурсии в данном решении не имею, это просто была дополнительная информация)
Но да, без рекурсии решение получается универсальным и работает несколько быстрее за счет экономии времени на вызовах функции.

2021-10-03 11:20 UTC, OlgaLavrenteva commented on Practice/olavrenteva/practice4/task6.py
> +            exclude_column(lst, value)
Я не сразу поняла куда именно предлагается добавить break - подумала, что не внутри if, а после и тогда это ломало логику. А если внутри, то да, согласна и добавила.

2021-10-03 14:00 UTC, IlyaOrlov approved these changes

2021-10-03 14:00 UTC, merged