Mryzhov branch
IlyaOrlov/PythonCoursePro pull request #34
Opened 2021-10-04 21:18 UTC by max-ryzhov

дз по 3й лекции: 
- образование числа из  введенных цифр;
- палиндром.

2021-10-05 12:27 UTC, IlyaOrlov requested changes

2021-10-05 12:27 UTC, IlyaOrlov commented on Practice/mryhzov/lec_3_palindrom.py
> +    half_2 = w[(half_len+1):len_str]
Не сработает для палиндрома из четного количества символов: ```Слово "алла" - не является палиндромом```

2021-10-05 12:27 UTC, IlyaOrlov commented on Practice/mryhzov/lec_3_palindrom.py
> +    if half_1 in half_2[::-1]:     # сравнил первую половину с перевернутой второй
Чем in лучше более очевидного ==?
Можно, кстати, сразу выполнить return half_1 in half_2[::-1] или return half_1 == half_2[::-1]

2021-10-05 12:27 UTC, IlyaOrlov commented on Practice/mryhzov/lec3_word_to_number.py
> +        num = num + a
Лучше короче: num += a
То же самое в стр. 22

2021-10-05 13:03 UTC, IlyaOrlov requested changes

2021-10-05 13:03 UTC, IlyaOrlov commented on Practice/mryhzov/lec3_secret_number.py
> +def rand(x, y):      # Загадываем число
В чем тайный смысл этой функции?

2021-10-07 20:31 UTC, IlyaOrlov requested changes

2021-10-07 20:31 UTC, IlyaOrlov commented on Practice/mryhzov/lec_4/FizzBuzz.py
> +for i in list1:
Почему бы сразу не пойти по range(1, 101), без list1.

2021-10-10 19:29 UTC, max-ryzhov commented on Practice/mryhzov/lec_3_palindrom.py
> +    half_2 = w[(half_len+1):len_str]
поправил

2021-10-10 19:32 UTC, max-ryzhov commented on Practice/mryhzov/lec3_word_to_number.py
> +        num = num + a
поправил

2021-10-11 10:17 UTC, IlyaOrlov commented on Practice/mryhzov/lec_3_palindrom.py
> +    return w == w[::-1]  # сравнил слово с самим сосбой перевернутым
OK, но нужно понимать, что это не самая быстрая реализация. Сравнивать половины слова быстрее.
Также стоит предусмотреть следующий вариант (согласно заданию) - "Топот" - когда слово начинается с большой буквы и является палиндромом.

2021-10-11 10:19 UTC, IlyaOrlov commented on Practice/mryhzov/lec_4/dictionary.py
> +    val = dic[key]    # значение по конкретному ключу(строка)
Если нужны и key, и val, то лучше идти по dic.items().

2021-10-11 10:23 UTC, IlyaOrlov commented on Practice/mryhzov/lec_4/lec4_sorted.py
> +    lst2.append(min_num)
9 и 10 можно объединить в lst2.append(lst1.pop(ind_min)), т.к. pop не только удаляет из списка, но и возвращает указанный элемент.

2021-10-11 10:25 UTC, IlyaOrlov commented on Practice/mryhzov/lec_4/lec4_sorted.py
> +while i <= 5:
Не надо завязываться на конкретные числа! Это снижает универсальность алгоритма. Есть функция для получения длины списка.

2021-10-11 10:26 UTC, IlyaOrlov commented on Practice/mryhzov/lec_4/lec4_sorted.py
> +lst2 = []    # Не смог корректно реализовать замену символов в первичном списке, ввел второй
Все-таки стоит попробовать реализовать согласно алгоритму в задании. Если не получится - разберем, в чем конкретно загвоздка.

2021-10-13 12:07 UTC, IlyaOrlov commented on Practice/mryhzov/lec_5/class_Man.py
> +        self.name = name
Планируем ли мы доступ к атрибуту name вне класса?

2021-10-16 15:25 UTC, IlyaOrlov requested changes

2021-10-16 15:25 UTC, IlyaOrlov commented on Practice/mryhzov/lec_3_palindrom.py
> +    half_len = int(len_str // 2)
К int приводить не нужно. Результат целочисленного деления - и так целое число.

2021-10-16 15:25 UTC, IlyaOrlov commented on Practice/mryhzov/lec_3_palindrom.py
> +        half_1 = w[0:half_len]
Очевидно half_1 можно вынести за скобки (за блок if) и 0 указывать необязательно (по умолчанию, срез и так начинается с 0). Так же, как и len_str в качестве конца среза.

2021-10-16 15:25 UTC, IlyaOrlov commented on Practice/mryhzov/lec_4/dictionary.py
> +for key_val in dic.items():    # key_val - кортеж (key, val)
Можно сразу так: 
```python
for key, val in dic.items():
```

2021-10-18 12:16 UTC, IlyaOrlov commented on Practice/mryhzov/lec_3_palindrom.py
> +    if len_str % 2 == 0:
Еще бы немножко упростить:
```python
def check_pal(w):
    len_str = len(w)
    half_len = len_str // 2
    half_1 = w[:half_len]
    half_2 = w[half_len:] if len_str % 2 == 0 else w[half_len + 1:]
    return half_1 == half_2[::-1]
```

2021-10-19 10:31 UTC, merged