Practice 6, Practice 7 task 5
IlyaOrlov/PythonCoursePro pull request #49
Opened 2021-10-14 14:16 UTC by elenabessonova56

2021-10-14 15:04 UTC, IlyaOrlov requested changes

2021-10-15 15:12 UTC, elenabessonova56 commented on Practice/ebessonova/practice_7/task_5.py
> +s1 = re.compile(r'\: git .*')
два вызовов compile  оставила, так как необходимо одновременно задавать условия начала и конца строки, выражения типа [: |"] в начале и конце регулярного выражения дают много лишних символов в итоговой строке

2021-10-16 15:03 UTC, IlyaOrlov commented on Practice/ebessonova/practice_6/suppl_task_1.py
> +    return iter(text)
Да, теперь логика правильная!

2021-10-16 15:08 UTC, IlyaOrlov requested changes

2021-10-16 15:08 UTC, IlyaOrlov commented on Practice/ebessonova/practice_6/suppl_task_1.py
> +            if buffer[len(buffer) - len(self.__paragraph_symbol):len(buffer)] == self.__paragraph_symbol:
Можно так: buffer[-len(self.__paragraph_symbol):] == self.__paragraph_symbol, а еще лучше так: buffer.endswith(self.__paragraph_symbol)

2021-10-16 15:08 UTC, IlyaOrlov commented on Practice/ebessonova/practice_6/suppl_task_1.py
> +        print(next(p))
Можно итератор и так обойти (без необходимости отлавливать исключение):
```python
for p in ParagraphIter(f, 'Paragraph'):
    print(p)
```

2021-10-17 17:57 UTC, IlyaOrlov approved these changes

2021-10-17 17:57 UTC, merged