Mryzhov branch
IlyaOrlov/PythonCoursePro pull request #5
Opened 2021-09-19 08:32 UTC by max-ryzhov

Эхо-скрипт, работа с репозиторием

2021-09-21 20:48 UTC, IlyaOrlov requested changes

2021-09-21 20:48 UTC, IlyaOrlov commented on Practice/mryhzov/echo_script.py
> +print('Неужели это {} {}?!'.format(user_name, user_surname))
Гораздо изящнее получится, если использовать форматную строку:
```python
print(f'Неужели это {user_name} {user_surname}?!')
```

2021-09-27 09:14 UTC, max-ryzhov commented on Practice/mryhzov/echo_script.py
> +print('Неужели это {} {}?!'.format(user_name, user_surname))
поправил. переименовал файл в lec1_echo_script.py

2021-09-27 11:46 UTC, IlyaOrlov requested changes

2021-09-27 11:46 UTC, IlyaOrlov commented on Practice/mryhzov/lec2_comparison.py
> +    return a    # 4. возвращаем результат выполнения функции в глобальное пространство
Функция будет более предсказуемой, если все ее результаты будут иметь один тип (т.е. всегда числа, или всегда строки, или специальное значение None).

2021-10-01 20:13 UTC, closed without merging

2021-10-01 21:48 UTC, IlyaOrlov commented
А что закрыли? Хороший Pull Request был)