Achulkova
IlyaOrlov/PythonCoursePro pull request #6
Opened 2021-09-20 08:39 UTC by anastasiachulkova

2021-09-21 20:49 UTC, IlyaOrlov requested changes

2021-09-21 20:49 UTC, IlyaOrlov commented on Practice/achulkova/pep8task.py
> +import sys
Хотелось бы увидеть комментарии: где, что и почему поменяли.

2021-09-23 19:21 UTC, IlyaOrlov requested changes

2021-09-23 19:21 UTC, IlyaOrlov commented on Practice/achulkova/pep8task.py
> +            f = open(output, 'r') #неправильный отступ
Отступ в строках 24 и 25, конечно, неправильный. Но, вот, от того, избыточный он или недостаточный, зависит, будет ли содержимое self.map перезаписываться в файл на каждой итерации цикла, или всего один раз уже после цикла. Как будет лучше?

2021-09-26 07:27 UTC, anastasiachulkova commented on Practice/achulkova/pep8task.py
> +            f = open(output, 'r') #неправильный отступ
Отступы поправила - вынесла перезапись в файл из цикла, так чтобы self.map записывался один раз

2021-09-26 10:49 UTC, IlyaOrlov approved these changes

2021-09-26 10:49 UTC, merged