Ebessonova
IlyaOrlov/PythonCoursePro pull request #68
Opened 2021-10-29 06:54 UTC by elenabessonova56

2021-10-30 15:12 UTC, elenabessonova56 commented on Practice/ebessonova/practice_10/task_2_client.py
> +    def __repr__(self):
__str__ отвечает за строковое представление объектов класса в удобочитаемом виде
__repr__ нужен для строкового представления класса в виде удобном разработчику

В данной задаче, думаю, правильнее использовать перегруженную функцию __str__, так как сервер выводит информацию о юзере для чтения

2021-10-31 10:49 UTC, IlyaOrlov commented on Practice/ebessonova/practice_10/task_2_client.py
> +    def __repr__(self):
Согласен.

2021-10-31 10:54 UTC, IlyaOrlov commented on Practice/ebessonova/practice_10/task_1_server.py
> +s.close()
Это значит, что можно его использовать, например, так:
```python
with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
...
```
Уже без необходимости явного вызова close()

2021-10-31 10:58 UTC, IlyaOrlov requested changes

2021-10-31 10:58 UTC, IlyaOrlov commented on Practice/ebessonova/practice_9/task_2.py
> +    if type(args[0]) == int:
Можно несколько упростить пример: sum = type(args[0])()
Но стоит проверить, что type(args[0]) in {int, list, str}

2021-10-31 15:58 UTC, IlyaOrlov approved these changes
Все отлично!

2021-10-31 16:01 UTC, IlyaOrlov commented
Только надо ещё конфликт в файле Practice/ebessonova/practice_9/task_2.py зарезолвить.

2021-11-01 10:43 UTC, merged