Ebessonova: Practice 11 task 1
IlyaOrlov/PythonCoursePro pull request #76
Opened 2021-11-04 18:53 UTC by elenabessonova56

2021-11-05 10:09 UTC, IlyaOrlov requested changes

2021-11-05 10:09 UTC, IlyaOrlov commented on Practice/ebessonova/practice_11/task_1.py
> +        self.__conn.execute('CREATE TABLE COMPANY'
Чтоб SQLiteWrapper был универсальным и мог использоваться в т.ч. для существующих баз, SQL-запрос для создания таблицы стоит вынести из этого класса. Конфигурирование не относится к задачам SQLiteWrapper.

2021-11-05 10:09 UTC, IlyaOrlov commented on Practice/ebessonova/practice_11/task_1.py
> +            for row in cursor:
Непонятно, почему нельзя просто получить список из row и применить к нему json.dumps, или открыть файл на дозапись и скидывать туда json.dumps(row).

2021-11-05 16:14 UTC, elenabessonova56 commented on Practice/ebessonova/practice_11/task_1.py
> +            for row in cursor:
Сделала это, чтобы json был более информативным, содержал наборы поле:значение. Если добавлять просто row, то будут только наборы значений без названия полей.

2021-11-06 08:26 UTC, IlyaOrlov requested changes

2021-11-06 08:26 UTC, IlyaOrlov commented on Practice/ebessonova/practice_11/task_1.py
> +            for row in cursor:
Есть решение проще:
```python
    def select(self, sql_req):
        self.__conn.row_factory = sqlite3.Row  # позволяет возвращать в т.ч. и названия полей
        cursor = self.__conn.execute(sql_req)
        with open('data.json', 'w') as f:
            for row in cursor:
                json.dump(dict(row), f)  # row нужно преобразовать в dict, чтоб можно было сериализовать в json

```

2021-11-06 08:26 UTC, IlyaOrlov commented on Practice/ebessonova/practice_11/task_1.py
> +    conn.execute('CREATE TABLE COMPANY'
Если база сохраняется в файле, имеет смысл добавить проверку на существование этой базы (файла), чтоб не пытаться лишний раз пересоздать таблицу и снова наполнить ее данными. Это также облегчит перезапуск скрипта.

2021-11-06 10:07 UTC, elenabessonova56 commented on Practice/ebessonova/practice_11/task_1.py
> +            for row in cursor:
спасибо! исправила

2021-11-06 18:14 UTC, IlyaOrlov approved these changes
Теперь все ОК! Хотя предполагалось, что независимость программы от SQLite/MySQL/PostgreSQL в task_2.py будет обеспечена реализацией через ORM (например, SQLAlchemy), но можно ограничиться и таким вариантом.

2021-11-06 18:14 UTC, merged