(Olga Lavrenteva) Practice#13 task#1
IlyaOrlov/PythonCoursePro pull request #80
Opened 2021-11-10 21:14 UTC by OlgaLavrenteva

2021-11-11 21:16 UTC, IlyaOrlov commented on Practice/olavrenteva/practice13/task1.py
> +    convert_dict = {
Этот словарь лучше вынести из функции и оформить, как константу (большими буквами). Чтоб он не пересоздавался в памяти при каждом вызове функции.

2021-11-11 21:20 UTC, IlyaOrlov requested changes
Тесты получились идеальные!!!
Только один минорный комментарий по самой функции to_roman.

2021-11-12 16:49 UTC, OlgaLavrenteva commented on Practice/olavrenteva/practice13/task1.py
> +    convert_dict = {
Сделала, спасибо

2021-11-12 16:52 UTC, OlgaLavrenteva commented
**Coverage report for task2**

_To generate:_

pytest -v tests.py --cov-report html:cov_html --cov task2

_Summary:_

<img width="560" alt="Screenshot 2021-11-12 at 19 50 24" src="https://user-images.githubusercontent.com/47915018/141504116-804af939-38ed-4cee-9d3a-b54e1ef7ec63.png">

2021-11-13 09:42 UTC, IlyaOrlov approved these changes
Проверил. Еще и покрытие 100% 
Просто ОГОНЬ!!!

2021-11-13 09:43 UTC, merged